url_shortener/models.py
import string
from datetime import datetime
from random import choices
from .extensions import db

class Link(db.Model):
    __tablename__ = 'link'

    id = db.Column(db.Integer, primary_key=True)
    original_url = db.Column(db.String(512))
    short_url = db.Column(db.String(3), unique=True)
    visits = db.Column(db.Integer, default=0)
    date_created = db.Column(db.DateTime, default=datetime.now)

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.short_url = self.generate_short_link()

    def generate_short_link(self):
        characters = string.digits + string.ascii_letters
        short_url = ''.join(choices(characters, k=3))

        link = self.query.filter_by(short_url=short_url).first()


        if link:
            return self.generate_short_link()
        
        return short_url

url_shortener/__init__.py
from flask import Flask

from .extensions import db
from .routes import short

app = Flask(__name__)

app.config.from_pyfile('settings.py')

db.init_app(app)

app.register_blueprint(short)

#app.config['SQLALCHEMY_DATABASE_URI'] = 'postgres://oadzoiwprhukgt:c3f5331f6c3ab1f84ce76fa5c3222d07f9c6e4465a726d1c4a69fc1759c8fda0@ec2-52-31-233-101.eu-west-1.compute.amazonaws.com:5432/d5kvgr76ueoke1'

#app.config.from_object('config')


def create_app(config_file='settings.py'):
    app = Flask(__name__)

    app.config.from_pyfile(config_file)

    db.init_app(app)

    app.register_blueprint(short)


    return app

url_shortener/auth.py
from functools import wraps
from flask import request, Response, current_app


def check_auth(username, password):
    """This function is called to check if a username /
    password combination is valid.
    """
    return username == 'admin' \
        and password == 'password'

def authenticate():
    """Sends a 401 response that enables basic auth"""
    return Response(
    'Could not verify your access level for that URL.\n'
    'You have to login with proper credentials', 401,
    {'WWW-Authenticate': 'Basic realm="Login Required"'})

def requires_auth(f):
    @wraps(f)
    def decorated(*args, **kwargs):
        auth = request.authorization
        if not auth or not check_auth(auth.username, auth.password):
            return authenticate()
        return f(*args, **kwargs)
    return decorated

url_shortener/routes.py
from flask import Blueprint, render_template, request, redirect

from .extensions import db
from .models import Link

from .auth import requires_auth

short = Blueprint('short', __name__)

@short.route('/<short_url>')
def redirect_to_url(short_url):
    link = Link.query.filter_by(short_url=short_url).first_or_404()

    link.visits = link.visits + 1
    db.session.commit()

    return redirect(link.original_url)

@short.route('/')
@requires_auth
def index():
    return render_template('index.html')

@short.route('/add_link', methods=['POST'])
@requires_auth
def add_link():
    original_url = request.form['original_url']
    link = Link(original_url=original_url)
    db.session.add(link)
    db.session.commit()

    return render_template('link_added.html', new_link=link.short_url, original_url=link.original_url)

@short.route('/stats')
@requires_auth
def stats():
    links = Link.query.all()

    return render_template('stats.html', links=links)

@short.errorhandler(404)
def page_not_found(e):
    return render_template('404.html'), 404

url_shortener/templates/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Url Shorten</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
</head>

<body>
    <section class="section">
        <div class="container">
            <form method="POST" action="{{ url_for('short.add_link') }}">
                <div class="field">
                    <label class="label">Original URL &nbsp;&nbsp;&nbsp;</label>

                    <div class="control">
                        <input class="input" type="text" name="original_url" placeholder="Original URL" required>
                    </div>
                </div>
                <div class="control">
                    <button type="submit" class="button is-danger is-outlined">
                        Shorten
                    </button>
                </div>
                <br />
            </form>
            <div class="control">
                <form action="stats">
                <button type="submit" class="button is-link is-outlined">
                    View list of Url's
                </button>
                </form>
            </div>
        </div>
    </section>
</body>

</html>

url_shortener/templates/link_added.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Url Shorten</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
</head>

<body>
    <section class="section">
        <div class="container">

            <div class="field">
                <label class="label">Original URL</label>
                <div class="control">
                    <input class="input" type="text" value="{{ original_url }}">
                </div>
            </div>

            <br/>
            <div class="field">
                <label class="label">Shorten URL</label>
                <div class="control">
                    <input class="input" type="text"
                        value="{{ url_for('short.redirect_to_url', short_url=new_link, _external=True) }}">
                </div>
            </div>
            <br/>
            <div class="control">
            <form action="/">
            <button type="submit" class="button is-link is-outlined">
               Go to Home
            </button>
          </form>
          </div>
        </div>
        
    </section>
</body>

</html>

url_shortener/templates/stats.html
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Url Shorten</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.0/css/bulma.min.css">
</head>

<body>
  <section class="section">

    <div class="container">

      <div class="control">
        <form action="/">
          <button type="submit" class="button is-link is-outlined">
            Go to Home
          </button>
        </form>
        <br />
        <form action="/stats">
          <button class="button is-success is-outlined">Reload</button>
        </form>
      </div>
      <br />

      <table class="table is-bordered is-striped is-narrow is-hoverable">
        <thead>
          <tr>
            <th>Original URL</th>
            <th>Shorten URL</th>
            <th>Visits count</th>
          </tr>
        </thead>

        <tbody>
          {% for link in links %}
          <tr>
            <td> {{ link.original_url }} </td>
            <td> {{ url_for('short.redirect_to_url', short_url=link.short_url, _external=True) }} </td>
            <td> {{ link.visits }} </td>

            {% endfor %}
          </tr>

        </tbody>

      </table>


    </div>
  </section>
</body>

</html>